### ISSUE TITLE
Erro: cannot crop to trim box. 

### ISSUE THREAD

**Issue by wouter-asterisk** [mike-edel/ID-MultiPageImporter#5] opened 2018-11-08 09:41 UTC
Ether the trim box is not defined, or is empty.

**Comment by wouter-asterisk** [comment] 2018-11-08 09:42
Javascript error!

Error number: 89867
Error String: The default enige 'main' cannot be deleted.

Enige: main
File: multipageimporter.2.6.1.jsx
Line: 581
Source:    Excit(-1);

**Comment by mike-edel** [comment] 2018-11-08 10:08
Sorry, only just saw this over here and replied to the thread on InDesignSecrets.

As far as I'm aware there is no general problem with the script on the latest version of InDesign.
This rather sounds like an issue with the pdf you try to place - saw a few other cases like this in the past.

To check if that's the case::
* Can you try to manually place the same pdf with the same settings (crop to trim)?
* Alternatively, try with a file that’s known good.

If all of that fails it would be helpful if you could provide me with the file in question so I can reproduce the issue. Would also be helpful to get some info on your system (Windows/Mac, InDesign version as shown in Help->About InDesign)

**Comment by mike-edel** [comment] 2019-01-14 10:05
Closing as I can't reproduce here and as I would need some more details. I suspect it's a file issue with the PDF. Will re-open once I have something reproducible.

**Closed by mike-edel** 2019-01-14 10:05 UTC
